# Generated by Django 5.0.6 on 2024-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=15)),
                ('last_Name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('instrument', models.CharField(max_length=100)),
            ],
        ),
    ]
